FROM docker.io/library/caddy:2-alpine

COPY frontend/Caddyfile /etc/caddy/Caddyfile
COPY frontend/index.html /srv/index.html
COPY frontend/app.js /srv/app.js
COPY frontend/style.css /srv/style.css

USER 1000
EXPOSE 8080

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
