FROM docker.io/library/nginx:1.30.4-alpine
LABEL io.todo.frontend="nginx"

COPY todo-frontend/nginx.conf /etc/nginx/nginx.conf
COPY todo-frontend/index.html /usr/share/nginx/html/index.html
COPY todo-frontend/app.js /usr/share/nginx/html/app.js
COPY todo-frontend/auth.js todo-frontend/keycloak-adapter.js /usr/share/nginx/html/
COPY todo-frontend/style.css /usr/share/nginx/html/style.css
COPY todo-frontend/vendor /usr/share/nginx/html/vendor

USER nginx
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
