apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-postgres-config
data:
  POSTGRES_DB: notes
  POSTGRES_USER: notes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notes-backend-config
data:
  DATABASE_HOST: notes-postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: notes
  DATABASE_USER: notes_app
  LOG_LEVEL: {{ .Values.runtime.logLevel | quote }}
  OIDC_ISSUER: {{ printf "https://%s:%v/auth/realms/todo" .Values.runtime.publicHostname .Values.runtime.publicPort | quote }}
  OIDC_JWKS_URL: http://keycloak:8080/auth/realms/todo/protocol/openid-connect/certs
  OIDC_AUDIENCE: notes-frontend
