apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-postgres-config
data:
  POSTGRES_DB: todo
  POSTGRES_USER: todo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
data:
  DATABASE_HOST: todo-postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: todo
  DATABASE_USER: todo_app
  LOG_LEVEL: {{ .Values.runtime.logLevel | quote }}
  OIDC_ISSUER: {{ printf "https://%s:%v/auth/realms/todo" .Values.runtime.publicHostname .Values.runtime.publicPort | quote }}
  OIDC_JWKS_URL: http://keycloak:8080/auth/realms/todo/protocol/openid-connect/certs
  OIDC_AUDIENCE: todo-frontend
